### ISSUE TITLE
Ideas & Improvments

### ISSUE THREAD

**Issue by theoludwig** [ideas-to-dev/ideas-to.dev#10]
Salut, 

Je me permets d'écrire en français, car j'ai vu que tu es français.
Si tu as envie de ne pas "polluer" les issues, je peux continuer en Anglais. 😉
Je trouve ton idée superbe, parfait pour avoir de l'inspiration.

Problèmes ou éléments à améliorer :
- Le site n'a pas de favicon, ce n'est pas très bon pour le référencement, ça peut être une simple ampoule 💡 par exemple.
- Le site en ligne actuel ne dispose pas de la version build de React, c'est l'environnement de développement ce qui cause des performances désastreuses au site.
- Le site est en anglais, mais les idées sont en français c'est incohérent, on ne sait pas si on doit publier les idées en français ou en anglais, bon comme tu le dit dans cette [issue](https://github.com/ideas-to-dev/ideas-to.dev/issues/7), c'est prévu que ça change.
Donc c 'est un site qui prévoit d'être multilangue ? Ou seulement anglais ?
- Il n'y a pas le lien du GitHub, c'est pas très agréable pour l'utilisateur. Il devrait avoir le lien vers le repo GitHub (peut-être sur le footer ?).

Il y a un repo Anglais qui a le même principe, tu peux t'en inspirer, d'ailleurs je préfère une version web, qu'une version sur GitHub. [https://github.com/florinpop17/app-ideas](https://github.com/florinpop17/app-ideas)

Sinon oui, je suis complétement d'accord avec cette fonctionnalité : 
"Present your GitHub projects below an idea.", comme ça tout le monde peut partager sa version à lui de l'idée.

J'ai proposé une idée sur le site directement (en français). 😎
Avec plaisir de contribuer, je n'ai pas beaucoup de connaissances PHP mais en JavaScript pourquoi pas.

Bonne continuation,

**Comment by brandonsueur** [comment]
Bonjour @Divlo,

> Le site n'a pas de favicon, ce n'est pas très bon pour le référencement, ça peut être une simple ampoule 💡 par exemple.

Effectivement, j'y ai pensé mais je dois faire un petit logo. Même si, entretemps je pourrais mettre l'ampoule en favicon. 

> Le site en ligne actuel ne dispose pas de la version build de React, c'est l'environnement de développement ce qui cause des performances désastreuses au site.

Oui je l'ai fait pour la première fois mais je dois faire des actions sur GitHub afin qu'il puissent le faire automatiquement.

> Le site est en anglais, mais les idées sont en français c'est incohérent, on ne sait pas si on doit publier les idées en français ou en anglais, bon comme tu le dit dans cette issue, c'est prévu que ça change.
Donc c 'est un site qui prévoit d'être multilangue ? Ou seulement anglais ?

Le site sera entièrement en Anglais je pense ou alors multilangue, à voir dans les jours à suivre quand je ferais la feature.

> Il n'y a pas le lien du GitHub, c'est pas très agréable pour l'utilisateur. Il devrait avoir le lien vers le repo GitHub (peut-être sur le footer ?).

Une très bonne idée, je n'y avais pas du tout pensé ! Merci @Divlo !

> J'ai proposé une idée sur le site directement (en français). 😎

Génial ! 🚀 Je regarde ça au plus vite et elle sera disponible dans les plus brefs délais.

Merci pour ta contribution, ça fait plaisir d'avoir d'autres retours. ☺️
