### ISSUE TITLE
Lien web

### ISSUE THREAD

**Issue by BuyukCem** [ideas-to-dev/ideas-to.dev#4]
Bonjour,
Le lien du site ne fonctionne pas est-ce normal?

**Comment by brandonsueur** [comment]
Bonjour,

Effectivement, c'est normal avant de lancer le site, je souhaite déjà collecter des idées dans ce [dépôt](https://github.com/ideas-to-dev/ideas).

Le site sortira dans les jours à suivre. 🙂
