### ISSUE TITLE
Problème affichage catégorie

### ISSUE THREAD

**Issue by qaniere** [ideas-to-dev/ideas-to.dev#5]
Bonjour, sur mon écran (1920 x 1080), les catégories ne s'affichent pas correctement.

![image](https://user-images.githubusercontent.com/63805908/81834564-62ba2280-9541-11ea-9822-b6669c3fd47b.png)

**Comment by brandonsueur** [comment]
Bonjour Quentin,

Merci d'avoir reporté ce bug, je corrige ça ce soir 🙂

**Comment by brandonsueur** [comment]
J'ai résolu le problème, merci Quentin 👍
